### ISSUE TITLE
Joinコマンドを送信したテキストチャンネルだけ読み上げてほしい

### ISSUE THREAD

**Issue by lightsquall** [noriokun4649/Discord-TTS-Voice-channel-Bot#3]
作成者様
ありがたく利用させていただいています。

Docker版を利用しているのですが、
現状全てのテキストチャンネルが対象となりBotが読み上げてしまうため、
Joinコマンドが送信されたテキストチャンネルのみ読み上げ対象としてほしいです。

ご検討宜しくお願い致します。

**Comment by noriokun4649** [comment]
対応しました。

**Comment by lightsquall** [comment]
ありがとうございます！！！
