### ISSUE TITLE
Google 音声モードにすると、エラー

### ISSUE THREAD

**Issue by lightsquall** [noriokun4649/Discord-TTS-Voice-channel-Bot#4]
作成者様
いつもお世話になっております。

Google音声を楽しみにアプデしてみたのですが、以下エラーが出ましたので、念のため報告します。

GCPの無料サーバー(debian)にDocker-CEを入れ、その上で動作させています。
デプロイは、Portainerからコンテナを新規作成し、イメージの指定を「ghcr.io/noriokun4649/discord-tts-bot:1.0.1」
にしているだけです。

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
error ->
Error: Unable to parse audio data. Check your request params.
    at toBuffer (/var/docker/discord-tts-bot/node_modules/google-translate-tts/src/synthesize.js:48:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

r
Cannot read property '0' of undefined

d
TypeError: Cannot read property '0' of undefined
    at /var/docker/discord-tts-bot/voice_bot_node.js:175:101
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
NOT CONNECT
5秒後に再接続処理開始
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

以上、よろしくお願いいたします。

**Comment by noriokun4649** [comment]
仕様変更があったようで対応しました。

**Comment by lightsquall** [comment]
対応ありがとうございます！！
1.0.2でデプロイして動作確認しました！
次の機能追加をまったり楽しみにしています！
