### ISSUE TITLE
Feature Request: 複数サーバー対応

### ISSUE THREAD

**Issue by lightsquall** [noriokun4649/Discord-TTS-Voice-channel-Bot#5]
作者様
いつもお世話になっております。

普段利用させていただいております。

機能要望となります。
複数のDiscord Serverで同一のBotを導入した際、片方のServerで利用していると
もう片方のServerで利用できませんでした。

余力あれば将来的に対応いただけますと幸いです

**Comment by noriokun4649** [comment]
お久しぶりです。

こちらなのですが実は 7082f88cf95708251cf8ea49223cf3d7ad5f770d で処理を見なおしたので
複数のServerにて利用できるようになっていますがDocker Imageの方をreleaseしてなかったので
いまv1.0.4をリリースしました。ちょっとバグ残ってそうですが。。。

確認よろしくお願いします。

**Comment by lightsquall** [comment]
ありがとうございます！！
1.0.4に早速Updateしてみました。今のところ特に問題なさそうですが、もう少し使い続けてみます。
（これでサーバー毎にBotたててインスタンス立てなくてよくなるのでリソース的にとっても助かります・・・）

問題あれば別途報告させていただきます。
